export const sportIconNames = {
  "Boxing": "boxing",
  "3x3 Basketball": "ball-basketball",
  "Archery": "bow",
  "Artistic Gymnastics": "gymnastics",
  "Artistic Swimming": "artistic-swimming",
  "Athletics (Marathon)": "run",
  "Athletics (Race Walk)": "walk",
  "Athletics (Track & Field)": "run",
  "BMX Freestyle": "bike",
  "BMX Racing": "bike",
  "Badminton": "badminton",
  "Baseball": "ball-baseball",
  "Basketball": "ball-basketball",
  "Beach Volleyball": "ball-volleyball",
  "Boxing - Final Stages": "boxing",
  "Boxing - Preliminary Stages": "boxing",
  "Climbing": "climbing",
  "Cricket": "cricket",
  "Cycling Road (Road Race)": "bike",
  "Cycling Road (Time Trial)": "bike",
  "Cycling Track": "bike",
  "Diving": "diving",
  "Equestrian": "horse",
  "Fencing": "fencing",
  "Flag Football": "flag-football",
  "Football (Soccer)": "ball-football",
  "Golf": "golf",
  "Handball": "play-handball",
  "Hockey": "hockey",
  "Judo": "judo",
  "Lacrosse": "lacrosse",
  "Modern Pentathlon": "pentathlon",
  "Mountain Bike": "bike",
  "Open Water Swimming": "swimming",
  "Rhythmic Gymnastics": "rhythmic",
  "Rowing": "kayak",
  "Rowing Coastal Beach Sprints": "kayak",
  "Rugby Sevens": "rugby",
  "Sailing (Dinghy, Skiff & Multihull)": "sailboat",
  "Sailing (Windsurfing & Kite)": "windsurf",
  "Shooting (Rifle & Pistol)": "shooting",
  "Shooting (Shotgun)": "shooting",
  "Skateboarding (Park)": "skateboard",
  "Skateboarding (Street)": "skateboard",
  "Slalom Paddle": "kayak",
  "Softball": "ball-baseball",
  "Sprint Paddle": "kayak",
  "Squash": "squash",
  "Surfing": "surfing",
  "Swimming": "swimming",
  "Table Tennis": "ping-pong",
  "Taekwondo": "taekwondo",
  "Tennis": "ball-tennis",
  "Trampoline Gymnastics": "trampoline",
  "Triathlon": "triathlon",
  "Volleyball": "ball-volleyball",
  "Water Polo": "waterpolo",
  "Weightlifting": "barbell",
  "Wrestling": "wrestling"
};
