-- Audit rows are generated by a trigger after an admin changes a candidate.
-- The admin may update the candidate but must never gain direct audit-write access.
create or replace function public.set_qualification_review_audit()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.qualification_review_audit (candidate_id, action, note, record_snapshot, actor_id)
    values (new.id, 'created', null, new.confirmation_record, null);
  elsif old.status is distinct from new.status and new.status in ('approved', 'rejected') then
    insert into public.qualification_review_audit (candidate_id, action, note, record_snapshot, actor_id)
    values (new.id, new.status, new.resolution_note, new.confirmation_record, (select auth.uid()));
  end if;
  return new;
end;
$$;

-- This is trigger-only privileged code, not a public RPC endpoint.
revoke all on function public.set_qualification_review_audit() from public, anon, authenticated;
